# Generated by Django 5.2.1 on 2025-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='telebirr', max_length=50),
        ),
    ]
