# Generated by Django 5.2.1 on 2025-05-29 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(choices=[('sn', 'Science '), ('pl', 'ploitics'), ('ec', 'Economics'), ('it', 'Information Technology'), ('ar', 'Art'), ('ot', 'Other')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.category'),
        ),
    ]
